import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "@/app/globals.css"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Pagina restrita',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,}: {children: React.ReactNode}) 
  {
  return (
    <html lang="pt-br">
      <head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            <title>Página restrita</title>
            <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,500;1,400&display=swap" rel="stylesheet"/>
        </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
